name: QuantumSafe Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-quantumsafe:
    runs-on: ubuntu-latest

    env:
      OPENSSL_VERSION: 3.5.2
      LIBOQS_VERSION: 0.14.0
      OQSPROVIDER_VERSION: 0.10.0
      #WORKSPACE: ${{ github.workspace }}/quantumsafe
      WORKSPACE: ~/tmp
      BUILD_DIR: ${{ env.WORKSPACE }}/build
      INSTALLDIR_OPENSSL: /opt/openssl-${{ env.OPENSSL_VERSION }}
      INSTALLDIR_LIBOQS: /opt/liboqs
      INSTALLDIR_OQS_PROVIDER: /opt/oqs-provider
      DEFAULT_GROUPS: "x25519:p256_mlkem768:p384_mlkem768:mlkem768:mlkem1024:kyber768"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run QuantumSafe setup script
        run: |
          chmod +x prerequisites/quantumsafe/setup.sh
          ./prerequisites/quantumsafe/setup.sh

      - name: Test OpenSSL binary
        run: |
          $INSTALLDIR_OPENSSL/bin/openssl version -a
